# Prometheus Configuration for GitHub Actions Runners
# Monitors runner containers, host metrics, and GitHub Actions API

global:
  scrape_interval: 30s
  evaluation_interval: 30s
  external_labels:
    environment: "production" # Replace with your environment name or use envsubst/Docker Compose for substitution
    instance: "github-runner" # Replace with your instance name or use envsubst/Docker Compose for substitution

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

# Rules files
rule_files:
  - "/etc/prometheus/rules/*.yml"

# Scrape configurations
scrape_configs:
  # Prometheus self-monitoring
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
    scrape_interval: 15s

  # Node Exporter - Host metrics
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
    scrape_interval: 30s
    metrics_path: /metrics

  # cAdvisor - Container metrics
  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]
    scrape_interval: 30s
    metrics_path: /metrics

  # Docker daemon metrics (if enabled)
  - job_name: "docker"
    static_configs:
      - targets: ["host.docker.internal:9323"]
    scrape_interval: 30s
    metrics_path: /metrics

  # GitHub Runner application metrics
  - job_name: "github-runner"
    static_configs:
      - targets: ["runner:8080"]
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 10s

  # Custom GitHub API metrics (if webhook configured)
  - job_name: "github-webhook"
    static_configs:
      - targets: ["webhook:3000"]
    scrape_interval: 60s
    metrics_path: /metrics
