blank_issues_enabled: false
contact_links:
  - name: Security Issues
    url: https://github.com/GrammaTonic/github-runner/security/advisories/new
    about: Please report security vulnerabilities through GitHub Security Advisories
  - name: Discussions
    url: https://github.com/GrammaTonic/github-runner/discussions
    about: Ask questions and discuss ideas with the community
