name: Security Vulnerability (Trivy Finding)
description: Report a security vulnerability found by Trivy scanner
title: "[Security]: "
labels: ["security", "vulnerability", "trivy", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        🔒 **Security Vulnerability Report**

        This template is for reporting security vulnerabilities found by Trivy scanner.
        For manual security reports, use the main Security Policy process.

  - type: dropdown
    id: severity
    attributes:
      label: Severity Level
      description: What is the severity of this vulnerability?
      options:
        - CRITICAL
        - HIGH
        - MEDIUM
        - LOW
        - UNKNOWN
    validations:
      required: true

  - type: input
    id: cve-id
    attributes:
      label: CVE ID
      description: CVE identifier if available
      placeholder: e.g., CVE-2024-1234

  - type: input
    id: package
    attributes:
      label: Affected Package
      description: Which package/dependency is affected?
      placeholder: e.g., alpine:3.18, nginx:1.20, python:3.9
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Current Version
      description: Current version of the affected package
      placeholder: e.g., 3.18.0, 1.20.2
    validations:
      required: true

  - type: input
    id: fixed-version
    attributes:
      label: Fixed Version
      description: Version that fixes the vulnerability (if available)
      placeholder: e.g., 3.18.4, 1.21.0

  - type: dropdown
    id: scan-target
    attributes:
      label: Scan Target
      description: Where was this vulnerability found?
      options:
        - Dockerfile (filesystem scan)
        - Standard Runner Container
        - Chrome Runner Container
        - Base Image
        - Dependencies
        - Infrastructure Code
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Vulnerability Description
      description: Detailed description of the vulnerability
      placeholder: |
        - What is the vulnerability?
        - How could it be exploited?
        - What is the potential impact?
    validations:
      required: true

  - type: textarea
    id: trivy-output
    attributes:
      label: Trivy Scan Output
      description: Copy the relevant Trivy scan output
      render: shell
      placeholder: |
        Paste the Trivy scan results here...

        Example:
        library.so (alpine 3.18.0)
        ===========================
        Total: 1 (CRITICAL: 1, HIGH: 0, MEDIUM: 0, LOW: 0, UNKNOWN: 0)

        ┌────────────┬────────────────┬──────────┬────────────┬───────────────────┬─────────────────────────────────────────────────────────┐
        │  Library   │ Vulnerability  │ Severity │   Status   │ Installed Version │                         Title                           │
        ├────────────┼────────────────┼──────────┼────────────┼───────────────────┼─────────────────────────────────────────────────────────┤
        │ package    │ CVE-2024-1234  │ CRITICAL │   fixed    │ 1.2.3             │ Buffer overflow in package                              │
        └────────────┴────────────────┴──────────┴────────────┴───────────────────┴─────────────────────────────────────────────────────────┘
    validations:
      required: true

  - type: textarea
    id: remediation
    attributes:
      label: Proposed Remediation
      description: How should this vulnerability be fixed?
      placeholder: |
        - Update package to version X.Y.Z
        - Replace with alternative package
        - Apply security configuration
        - Add runtime mitigations
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Remediation Priority
      description: What priority should this have for fixing?
      options:
        - P0 - Critical (Fix immediately)
        - P1 - High (Fix within 1 week)
        - P2 - Medium (Fix within 1 month)
        - P3 - Low (Fix when convenient)
    validations:
      required: true

  - type: checkboxes
    id: impact-assessment
    attributes:
      label: Impact Assessment
      description: Check all that apply
      options:
        - label: Affects production deployment
        - label: Exploitable remotely
        - label: Requires authentication to exploit
        - label: Could lead to data compromise
        - label: Could lead to privilege escalation
        - label: Could cause denial of service
        - label: False positive (explain in description)

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any additional information about this vulnerability
      placeholder: |
        - Related issues or PRs
        - Workarounds currently in place
        - Dependencies that might be affected
        - Timeline constraints

  - type: checkboxes
    id: verification
    attributes:
      label: Verification Checklist
      description: Confirm the following before submitting
      options:
        - label: I have verified this is a legitimate security issue
        - label: I have checked if this CVE is already reported
        - label: I have assessed the impact on our specific use case
        - label: I have considered potential workarounds
        - label: I understand this will be tracked publicly (for non-sensitive issues)
          required: true
