# Grafana Provisioning Configuration
# Datasources for GitHub Actions Runner monitoring

datasources:
  # Prometheus datasource
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: 30s
      queryTimeout: 60s
      httpMethod: POST
      customQueryParameters: ""
    secureJsonData: {}

  # Loki for logs (optional)
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: false
    editable: true
    jsonData:
      timeout: 60s
      maxLines: 1000
