name: Auto Sync Docs

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  auto-sync-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # Need full history for diff against origin/main
          fetch-depth: 0
      - name: Check for outdated references in docs and wiki
        run: |
          # Search for the word 'template' but ignore known benign occurrences:
          # - files under docs/archive/ (historical notes)
          # - Prometheus console flag lines which include 'templates' as part of the flag
            if grep -rnI --line-number -E '\.template\b' docs/ wiki-content/ | grep -v -E '^docs/archive/|--web.console.templates=' > /tmp/outdated_refs.txt; then
            echo "❌ Outdated references found:"
            cat /tmp/outdated_refs.txt
            # Fail the job when running in CI
            exit 1
          else
            echo "✅ No outdated references found."
          fi
      - name: Validate Markdown links in docs and wiki
        run: |
          set -euo pipefail
          echo "Collecting markdown files (excluding docs/archive/)..."
          # Find docs markdown files but exclude archived docs
          mapfile -t DOCS_FILES < <(find docs -type f -name '*.md' ! -path 'docs/archive/*' -print0 2>/dev/null | xargs -0 -n1 echo)
          # Find wiki markdown files (may be empty)
          mapfile -t WIKI_FILES < <(find wiki-content -type f -name '*.md' -print0 2>/dev/null | xargs -0 -n1 echo || true)

          if [ ${#DOCS_FILES[@]} -gt 0 ]; then
            echo "Running markdown-link-check on ${#DOCS_FILES[@]} docs files..."
            npx markdown-link-check "${DOCS_FILES[@]}"
          else
            echo "No docs markdown files found to check."
          fi

          if [ ${#WIKI_FILES[@]} -gt 0 ]; then
            echo "Running markdown-link-check on ${#WIKI_FILES[@]} wiki files..."
            npx markdown-link-check "${WIKI_FILES[@]}"
          else
            echo "No wiki markdown files found to check."
          fi
      - name: Generate Documentation and Wiki Patch
        run: |
          git diff origin/main -- docs/ wiki-content/ > docs-wiki-full-patch.diff || echo "No doc or wiki changes detected."
      - name: Upload Docs and Wiki Patch Artifact
        uses: actions/upload-artifact@v4
        with:
          name: docs-wiki-full-patch
          path: docs-wiki-full-patch.diff
      - name: Create Pull Request for Docs and Wiki Updates
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "docs: automated documentation and wiki sync"
          title: "Automated Documentation and Wiki Sync"
          body: |
            This PR was created automatically to sync documentation and wiki blocks/examples with the latest code and workflow changes.
          # Use run-specific id for a unique branch name (shell substitution won't run here)
          branch: docs-wiki/auto-sync-${{ github.run_id }}
          base: main
