name: Auto Sync Docs

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  auto-sync-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check for outdated references in docs and wiki
        run: |
          grep -r -i 'template' docs/ wiki-content/ && exit 1 || echo "No outdated references found."
      - name: Validate Markdown links in docs and wiki
        run: |
          npx markdown-link-check docs/**/*.md
          npx markdown-link-check wiki-content/**/*.md
      - name: Generate Documentation and Wiki Patch
        run: |
          git diff origin/main -- docs/ wiki-content/ > docs-wiki-full-patch.diff || echo "No doc or wiki changes detected."
      - name: Upload Docs and Wiki Patch Artifact
        uses: actions/upload-artifact@v4
        with:
          name: docs-wiki-full-patch
          path: docs-wiki-full-patch.diff
      - name: Create Pull Request for Docs and Wiki Updates
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "docs: automated documentation and wiki sync"
          title: "Automated Documentation and Wiki Sync"
          body: |
            This PR was created automatically to sync documentation and wiki blocks/examples with the latest code and workflow changes.
          branch: docs-wiki/auto-sync-$(date +'%Y%m%d%H%M%S')
          base: main
