name: Auto Sync Docs

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  auto-sync-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check for outdated references
        run: |
          grep -r -i 'template' docs/ wiki-content/ && exit 1 || echo "No outdated references found."
      - name: Validate Markdown links
        run: |
          npx markdown-link-check docs/**/*.md
          npx markdown-link-check wiki-content/**/*.md
      - name: Generate Documentation Patch
        run: |
          git diff origin/main -- docs/ wiki-content/ > docs-full-patch.diff || echo "No doc changes detected."
      - name: Upload Patch Artifact
        uses: actions/upload-artifact@v3
        with:
          name: docs-full-patch
          path: docs-full-patch.diff
      - name: Create Pull Request for Doc Updates
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "docs: automated documentation sync"
          title: "Automated Documentation Sync"
          body: |
            This PR was created automatically to sync documentation blocks and examples with the latest code and workflow changes.
          branch: docs/auto-sync-$(date +'%Y%m%d%H%M%S')
          base: main
