name: Runner Self-Test Job

on:
  workflow_dispatch:

jobs:
  runner-test:
    name: Runner accepts jobs smoke test
    runs-on: [self-hosted, gh-runner-test]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run a small containerized echo test
        run: |
          echo "Runner $(hostname) is running a smoke test"
          uname -a
          echo "ok"

      - name: Chrome test (optional)
        if: always()
        run: |
          if command -v google-chrome >/dev/null 2>&1 || command -v chromium-browser >/dev/null 2>&1; then
            echo "Chrome available — running headless check"
            echo "about:blank" > /tmp/blank.html
            if command -v google-chrome >/dev/null 2>&1; then
              google-chrome --headless --disable-gpu --dump-dom file:///tmp/blank.html || true
            else
              chromium-browser --headless --disable-gpu --dump-dom file:///tmp/blank.html || true
            fi
          else
            echo "Chrome not present on this runner"
          fi
